Config = {}

Config.UseTarget = false

Config.Locations = {
    {
        control = vector3(-204.18, -1321.64, 31.29),
        vehicle = vector3(-198.85, -1324.42, 31.13),
        sprays = {
            { pos = vector3(-201.01, -1321.78, 31.13), rotation = vector3(0, 25, -90), scale = 1.2 },
            { pos = vector3(-197.49, -1321.78, 31.13), rotation = vector3(0, 25, -90), scale = 1.2 },
            { pos = vector3(-195.2, -1324.85, 31.13), rotation = vector3(0, 25, 180), scale = 1.2 },
            { pos = vector3(-195.2, -1323.96, 31.13), rotation = vector3(0, 25, 180), scale = 1.2 },
            { pos = vector3(-197.52, -1326.85, 31.13), rotation = vector3(0, 25, 90), scale = 1.2 },
            { pos = vector3(-201.13, -1326.85, 31.13), rotation = vector3(0, 25, 90), scale = 1.2 },
        },
        jobs =  false
    },
}

Config.SprayModel = 'prop_tool_nailgun'


Config.PearlescentColors = {
    { value = 0, label = "Black" },
    { value = 1, label = "Graphite" },
    { value = 2, label = "Black Steal" },
    { value = 3, label = "Dark Silver" },
    { value = 4, label = "Silver" },
    { value = 5, label = "Blue Silver" },
    { value = 6, label = "Rolled Steel" },
    { value = 7, label = "Shadow Silver" },
    { value = 8, label = "Stone Silver" },
    { value = 9, label = "Midnight Silver" },
    { value = 10, label = "Cast Iron Silver" },
    { value = 27, label = "Red" },
    { value = 28, label = "Torino Red" },
    { value = 29, label = "Formula Red" },
    { value = 30, label = "Lava Red" },
    { value = 31, label = "Blaze Red" },
    { value = 32, label = "Grace Red" },
    { value = 33, label = "Garnet Red" },
    { value = 34, label = "Sunset Red" },
    { value = 35, label = "Cabernet Red" },
    { value = 36, label = "Wine Red" },
    { value = 37, label = "Candy Red" },
    { value = 38, label = "Hot Pink" },
    { value = 39, label = "Pfsiter Pink" },
    { value = 40, label = "Salmon Pink" },
    { value = 41, label = "Sunrise Orange" },
    { value = 42, label = "Orange" },
    { value = 43, label = "Bright Orange" },
    { value = 44, label = "Gold" },
    { value = 46, label = "Yellow" },
    { value = 47, label = "Race Yellow" },
    { value = 48, label = "Dew Yellow" },
    { value = 49, label = "Dark Green" },
    { value = 50, label = "Racing Green" },
    { value = 51, label = "Sea Green" },
    { value = 52, label = "Olive Green" },
    { value = 53, label = "Bright Green" },
    { value = 54, label = "Gasoline Green" },
    { value = 55, label = "Lime Green" },
    { value = 56, label = "Midnight Blue" },
    { value = 57, label = "Galaxy Blue" },
    { value = 58, label = "Dark Blue" },
    { value = 59, label = "Saxon Blue" },
    { value = 60, label = "Blue" },
    { value = 61, label = "Mariner Blue" },
    { value = 62, label = "Harbor Blue" },
    { value = 63, label = "Diamond Blue" },
    { value = 64, label = "Surf Blue" },
    { value = 65, label = "Nautical Blue" },
    { value = 66, label = "Racing Blue" },
    { value = 67, label = "Ultra Blue" },
    { value = 68, label = "Light Blue" },
    { value = 69, label = "Chocolate Brown" },
    { value = 70, label = "Bison Brown" },
    { value = 71, label = "Creeen Brown" },
    { value = 72, label = "Feltzer Brown" },
    { value = 73, label = "Maple Brown" },
    { value = 74, label = "Beechwood Brown" },
    { value = 117, label = "Cream" },
    { value = 120, label = "Ice White" },
    { value = 121, label = "Frost White" },
    { value = 127, label = "Police Car Blue" },
    { value = 135, label = "Baby Blue" },
    { value = 136, label = "Bright Red" },
    { value = 138, label = "Gobo Red" },
    { value = 139, label = "Midnight Purple" },
    { value = 140, label = "Bright Purple" },
    { value = 141, label = "Schafter Purple" },
    { value = 143, label = "Dark Burgundy" },
    { value = 147, label = "Metallic Blue" },
    { value = 150, label = "Metallic Black" },
    { value = 152, label = "Metallic Green" },
    { value = 154, label = "Metallic Red" },
    { value = 156, label = "Chrome" },
}